definitions:
  handlers.SynchronizeRequestBody:
    properties:
      bucket_file_name:
        type: string
      bucket_name:
        type: string
    required:
    - bucket_file_name
    - bucket_name
    type: object
info:
  contact: {}
paths:
  /healthz:
    get:
      consumes:
      - '*/*'
      description: Health.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Health.
      tags:
      - Monitoring
  /readyz:
    get:
      consumes:
      - '*/*'
      description: Ready.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Ready.
      tags:
      - Monitoring
  /v1/map/{map_name}/generate:
    get:
      consumes:
      - application/json
      description: Generate json file from map file.
      parameters:
      - description: Map name
        in: path
        name: map_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Generate json file from map file.
      tags:
      - Map
  /v1/map/{map_name}/synchronize:
    post:
      consumes:
      - application/json
      description: Synchronize GCS file to an HAProxy map file.
      parameters:
      - description: Data of the synchronisation endpoint
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/handlers.SynchronizeRequestBody'
      - description: Map name
        in: path
        name: map_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Synchronize GCS file to an HAProxy map file.
      tags:
      - Map
swagger: "2.0"
